### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by mkermani144** [dai-shi/react-suspense-router#2]
When I try to use this package, I get this error:
```
TypeError: Cannot read property 'listen' of undefined
Class$S140: TypeError: Cannot read property 'listen' of undefined
```
It is caused by fork `useListen` custom hook.

**Comment by dai-shi** [comment]
Is it like `useListen` is not undefined, but `listen` is undefined?
I'm not sure how it happens. Can you describe more what you did please?

**Comment by mkermani144** [comment]
Yes, seems to be a problem here:  
https://github.com/dai-shi/react-router/blob/f07aabaf1137cdfe56c5971cedbd2c925729d499/packages/react-router/modules/index.js#L391  
that is, `React.useContext(LocationContext)` is undefined.  
I just upgraded to RR v6 following [this guide](https://github.com/ReactTraining/react-router/blob/dev/docs/advanced-guides/migrating-5-to-6.md). Then I replaced all imports of `react-router-dom` with `react-suspense-router`. Now I get the error.

**Comment by dai-shi** [comment]
I think I get it. You are using original RR6, which doesn't have useListen.
Please try uninstalling react-router-dom first, and then installing react-suspense-router. I think both npm and yarn work, but you could try another one if one doesn't work.

**Comment by mkermani144** [comment]
No, as I told you, `useListen` is defined. The problem is in the line I mentioned earlier. I have your fork version of RR, not the original version.

**Comment by dai-shi** [comment]
OK, I misunderstood that.
But, that means your `<Router>` is from the original version, not from the fork, doesn't it?
Will you try https://github.com/dai-shi/react-suspense-router-demo and see if it works in your environment?

**Comment by mkermani144** [comment]
Yes, you were right. The problem was that I was using a `HashRouter` (which uses original `Router` from RR internally). I simply changed it to `Router` from the fork and the app is working now. Thank you.

**Comment by dai-shi** [comment]
@mkermani144 
Doesn't `import { HashRouter } from 'react-suspense-router';` work then?

**Comment by mkermani144** [comment]
No, it doesn't work.

**Comment by dai-shi** [comment]
Hmm, I wasn't aware that.
I've only used `<BrowserRouter>` in the demo and examples and it works.

https://github.com/dai-shi/react-suspense-router/blob/89e1f66d805d8038b13b3873e72d944cc5da9c32/src/index.ts#L27-L28

They are just from the same place...

**Comment by mkermani144** [comment]
Neither `BrowserRouter` nor `HashRouter` works for me. That looks strange and may be a problem with my code base.

**Comment by dai-shi** [comment]
Yeah, you might want to compare yours with https://github.com/dai-shi/react-suspense-router-demo to find differences.
